#-----------------------------------------------------------------------------------
# Plugins for Neovim and Vim {{{
[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_ft = ['html']
hook_add = '''
  let g:user_emmet_leader_key = '<M-e>'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add = '''
  nnoremap <M-f> :NERDTreeToggle<CR>
'''
# }}}

#-----------------------------------------------------------------------------------
# Plugins for only Neovim {{{

[[plugins]]
repo = 'neoclide/coc.nvim'
if = "has('nvim')"
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
  source ~/.vim/plughook/coc-hook.vim
'''

[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft = ['markdown']
hook_add = '''
let g:instant_markdown_slow = 1
let g:instant_markdown_mathjax = 1
'''
# }}}
