
#-----------------------------------------------------------------------------------
# Plugins for Vim and Neovim {{{
[[plugins]] # プラグインマネージャ
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてfiletypeを切り替える
repo = 'osyo-manga/vim-precious'

[[plugins]] # カーソル位置のコンテキストのfiletypeを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # 囲える
repo = 'tpope/vim-surround'

[[plugins]] # 整形
repo = 'junegunn/vim-easy-align'
hook_add = '''
  nmap ga <Plug>(EasyAlign)
  xmap ga <Plug>(EasyAlign)
'''

[[plugins]] # 簡単にコメントトグル
repo = 'tpope/vim-commentary'

[[plugins]] # statusline をつよつよにする
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.vim/plughook/airline-hook.vim
'''

[[plugins]] # airline のテーマ
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
  let g:airline_theme='luna'
'''

# [[plugins]] # カッコやクォートの自動閉じなど
# repo = 'jiangmiao/auto-pairs'
# on_event = 'InsertEnter'

[[plugins]] # 行末の空白文字を削除するコマンドを追加
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_enabled = 0
  let g:strip_whitespace_on_save = 0
  let g:better_whitespace_filetypes_blacklist = ['txt', 'markdown', 'md']
'''

[[plugins]] # vim-surround とかの操作も . でリピートできるようにする
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_enabled = 1
  let g:indentLine_char = '¦'
'''
# }}}

#-----------------------------------------------------------------------------------
# Plugins for only Neovim {{{
[[plugins]] # terminalがもっと便利になる
repo = 'kassio/neoterm'
if = "has('nvim')"

[[plugins]] # なんかすごいやつ
repo = 'Shougo/denite.nvim'
if = "has('nvim')"

[[plugins]] # 便利なスニペット群
repo = 'Shougo/neosnippet-snippets'
if = "has('nvim')"

[[plugins]]
repo = 'dense-analysis/ale'
if = "has('nvim')"
hook_add = '''
  source ~/.vim/plughook/ale-hook.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
if = "has('nvim')"
hook_add = '''
  let g:EasyMotion_do_mapping = 0 " Disable default mappings
  let mapleader = "\<Space>"

  " `{char}{char}{label}`
  " Need one more keystroke, but on average, it may be more comfortable.
  nnoremap <leader><leader> <Plug>(easymotion-overwin-f2)

  " Turn on case-insensitive feature
  let g:EasyMotion_smartcase = 1

  " JK motions: Line motions
  " nmap <Leader>j <Plug>(easymotion-j)
      " nmap <Leader>k <Plug>(easymotion-k)
'''

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# if = "has('nvim')"
# hook_add = '''
# let g:indent_guides_enable_on_vim_startup = 1
# '''
# }}}

#-----------------------------------------------------------------------------------
# Syntax highlight {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'mboughaba/i3config.vim'
on_ft = ['i3config']

[[plugins]]
repo = 'zah/nim.vim'
on_ft = ['nim']
#}}}

#-----------------------------------------------------------------------------------
# Colorshemes {{{
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
  set background=dark
  let g:sonokai_enable_italic = 1
  let g:sonokai_style = 'shusia'
  au MyAutoCmd VimEnter * AirlineTheme sonokai
'''
# }}}
